"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowLeft, Mail, Phone, MapPin, Linkedin, Twitter, Facebook } from "lucide-react";
import { useTheme } from "@/components/theme-provider";
// ThemeToggle hidden — theme follows OS system preference automatically
// import { ThemeToggle } from "@/components/theme-toggle";
import logoBlue from "@/assets/logo-blue.png";
// import logoGold from "@/assets/logo-gold.png"; // gold disabled
import heroBlue from "@/assets/aiventra-logo-blue.png";
import heroBlueLight from "@/assets/aiventra-logo-blue-light.png";

const EASE = [0.16, 1, 0.3, 1] as const;

export default function TermsAndConditions() {
  const { theme } = useTheme();
  const logoSrc = logoBlue.src; // gold disabled
  const footerSrc = theme === "light" ? heroBlueLight.src : logoBlue.src;

  const footerLogoClass =
    theme === "light" ? "h-22 md:h-25 w-auto object-contain" : "h-16 md:h-18 w-auto object-contain";

  return (
    <div className="min-h-screen bg-background text-foreground relative pb-12 overflow-x-hidden">
      {/* Background radial highlights */}
      <div className="absolute inset-0 bg-hero opacity-80 pointer-events-none" />
      <div className="absolute top-1/4 right-0 h-[400px] w-[400px] rounded-full blur-[140px] opacity-10 pointer-events-none bg-primary" />

      {/* Navigation header bar */}
      <motion.header
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        className="fixed top-4 left-1/2 -translate-x-1/2 w-[calc(100%-2rem)] max-w-5xl z-45 rounded-2xl border border-border/40 bg-card/65 shadow-md backdrop-blur-xl px-4 py-3 flex items-center justify-between"
      >
        <Link href="/" className="flex items-center gap-2.5">
          <img src={logoSrc} alt="Aiventra Studio" className="h-8 md:h-9 w-auto object-contain" />
          <span className="font-display font-medium text-lg hidden sm:inline">Aiventra Studio</span>
        </Link>
        <div className="flex items-center gap-3">
          {/* ThemeToggle hidden — theme follows OS system preference automatically */}
          {/* <ThemeToggle /> */}
          <Link
            href="/"
            className="inline-flex items-center gap-2 rounded-lg border border-border px-4 py-2 text-sm font-medium hover:bg-surface transition-colors"
          >
            <ArrowLeft className="h-4 w-4" /> Back to Home
          </Link>
        </div>
      </motion.header>

      {/* Page Content */}
      <main className="pt-32 px-4 max-w-4xl mx-auto relative z-10">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, ease: EASE }}
          className="space-y-8"
        >
          <div className="space-y-4 text-center sm:text-left">
            <span className="text-xs uppercase tracking-widest text-primary font-semibold">
              Legal & Compliance
            </span>
            <h1 className="font-display text-4xl sm:text-5xl font-medium tracking-tight leading-tight">
              Terms &{" "}
              <span className="text-gradient font-display italic font-medium">Conditions.</span>
            </h1>
            <p className="text-muted-foreground text-sm">Last updated: July 10, 2026</p>
          </div>

          <div className="card-elevated p-6 sm:p-10 rounded-3xl border border-border/40 space-y-6 text-sm text-muted-foreground leading-relaxed">
            <section className="space-y-3">
              <h2 className="text-lg font-medium text-foreground">1. Agreement to Terms</h2>
              <p>
                By accessing our website, using our custom software estimation tools, or contracting
                with Aiventra Studios, you agree to be bound by these Terms & Conditions. If you do
                not agree, you are prohibited from using the platform.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-lg font-medium text-foreground">
                2. Estimates and Dynamic Pricing
              </h2>
              <p>
                Timelines, budget figures, and component listings generated by our Spec Builder tool
                are for estimation and planning purposes only. Final contracted prices, milestones,
                and deliverables will be formalised through a Statement of Work (SOW) signed by both
                parties.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-lg font-medium text-foreground">3. Intellectual Property</h2>
              <p>
                Unless stated otherwise in a signed SOW, all original design systems, source code
                templates, website layouts, and custom software architectures developed by Aiventra
                Studios remain our proprietary property until full contract payment is received, at
                which point ownership transfers as detailed in the contract.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-lg font-medium text-foreground">
                4. Support and Warranty (Aiventra Care)
              </h2>
              <p>
                Support SLAs, bug-fixing schedules, and minor adjustment scopes depend entirely on
                the selected Aiventra Care Plan (Standard, Care, or Care Pro) and the terms laid out
                in the SLA agreement. Standard plans cover launching defects for up to 3 months.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-lg font-medium text-foreground">5. Limitation of Liability</h2>
              <p>
                In no event shall Aiventra Studios or its directors, engineers, or cells be liable
                for any indirect, consequential, or incidental damages (including loss of profits,
                data breaches, or server downtime) arising from the deployment of our systems.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-lg font-medium text-foreground">6. Governing Law</h2>
              <p>
                These terms shall be governed by and defined in accordance with the laws applicable
                to our primary operational jurisdiction, without regard to conflict of law
                principles.
              </p>
            </section>

            <section className="space-y-3 pt-4 border-t border-border/20">
              <h2 className="text-lg font-medium text-foreground">Contact Us</h2>
              <p>
                For questions or clarifications regarding these Terms & Conditions, please contact
                us:
              </p>
              <div className="space-y-2 mt-2 font-medium text-foreground">
                <p className="flex items-center gap-2">
                  <Mail className="h-4 w-4 text-primary shrink-0" />
                  <a
                    href="mailto:hello@aiventrastudio.com"
                    className="hover:text-primary transition-colors"
                  >
                    hello@aiventrastudio.com
                  </a>
                </p>
                <p className="flex items-center gap-2">
                  <Phone className="h-4 w-4 text-primary shrink-0" />
                  <a href="tel:+2348085082246" className="hover:text-primary transition-colors">
                    +234 808 508 2246
                  </a>
                </p>
              </div>
            </section>
          </div>
        </motion.div>
      </main>

      {/* Footer */}
      <footer className="border-t border-border mt-20">
        <div className="container-page py-14 grid gap-10 md:grid-cols-4">
          <div className="md:col-span-2 space-y-4">
            <img src={footerSrc} alt="Aiventra Studios" className={footerLogoClass} />
            <p className="text-sm text-muted-foreground max-w-sm pt-2">
              Build. Innovate. Elevate. A studio of senior engineers and designers shipping
              world-class software.
            </p>
            <div className="flex items-center gap-3 pt-2">
              {[
                { icon: Linkedin, href: "https://www.linkedin.com/in/aiventra-studios-6b949441b/" },
                { icon: Twitter, href: "https://x.com/aiventrastudios?s=11" },
                {
                  icon: Facebook,
                  href: "https://www.facebook.com/profile.php?id=61591476395421&mibextid=wwXIfr",
                },
              ].map((soc, i) => {
                const Icon = soc.icon;
                return (
                  <a
                    key={i}
                    href={soc.href}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="grid h-9 w-9 place-items-center rounded-full border border-border text-muted-foreground hover:text-primary hover:border-primary transition-colors"
                  >
                    <Icon className="h-4 w-4" />
                  </a>
                );
              })}
            </div>
          </div>
          <div>
            <div className="text-xs uppercase tracking-wider text-foreground font-semibold mb-4">
              Navigate
            </div>
            <ul className="space-y-3">
              {[
                { label: "Home", href: "/#home" },
                { label: "About", href: "/#about" },
                { label: "Services", href: "/#services" },
                { label: "Portfolio", href: "/#portfolio" },
                { label: "Pricing", href: "/pricing" },
                { label: "Build Studio", href: "/build" },
                { label: "Contact", href: "/#contact" },
              ].map((n) => (
                <li key={n.href}>
                  <Link
                    href={n.href}
                    className="text-sm text-muted-foreground hover:text-primary transition-colors"
                  >
                    {n.label}
                  </Link>
                </li>
              ))}
            </ul>
          </div>
          <div>
            <div className="text-xs uppercase tracking-wider text-foreground font-semibold mb-4">
              Contact
            </div>
            <ul className="space-y-3 text-sm text-muted-foreground">
              <li>
                <a
                  href="mailto:hello@aiventrastudio.com"
                  className="hover:text-primary transition-colors"
                >
                  hello@aiventrastudio.com
                </a>
              </li>
              <li>
                <a href="tel:+2348085082246" className="hover:text-primary transition-colors">
                  +234 808 508 2246
                </a>
              </li>
              <li>Remote</li>
            </ul>
          </div>
        </div>
        <div className="border-t border-border">
          <div className="container-page py-6 flex flex-wrap items-center justify-between gap-4 text-xs text-muted-foreground">
            <span>© {new Date().getFullYear()} Aiventra Studios. All rights reserved.</span>
            <div className="flex gap-4">
              <Link href="/privacy" className="hover:text-primary transition-colors">
                Privacy Policy
              </Link>
              <Link href="/terms" className="hover:text-primary transition-colors">
                Terms & Conditions
              </Link>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
